root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
extends:
  - next
  - prettier
rules:
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  'react/prop-types': off
  'react/react-in-jsx-scope': off
overrides:
  - files: ['*.js']
    env: {node: true}
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['*.tsx']
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
